### ISSUE TITLE
Cannot destructure property 'url' of 'nestedModules.pop(...)' as it is undefined.

### ISSUE THREAD

**Issue by bergercookie** [alephjs/aleph.js#218]
I have a file called `user.ts` under the `api/` directory with the following contents:

```typescript
import type { APIRequest } from "https://deno.land/x/aleph/types.ts";

export default function handler(req: APIRequest) {
  console.log(`req: `, req);
  console.log(`req.params: `, req.params);
  console.log(`req.params.action: `, req.params.action);
  req.status(200).json({ name: req.params.action});
}
```

I'm making an HTTP GET request to it using [httpie](https://httpie.io/)

```ts
➜ http -v  localhost:8080/api/user action==all
GET /api/user?action=all HTTP/1.1 <--------------- Actual GET Request
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.8



HTTP/1.1 500 Internal Server Error
cache-control: max-age=0
content-length: 209
content-type: text/html; charset=utf-8
date: Sun, 28 Mar 2021 09:05:39 GMT
server: Aleph.js

<!DOCTYPE html><title>500 - internal server error</title><p><strong><code>500</code></strong><small> - </small><span>Cannot destructure property 'url' of 'nestedModules.pop(...)' as it is undefined.</span></p>

```

Meanwhile, I can avoid getting a 500 error, only If I put this file under `api/user/[name].ts`, but in this case, it bundles the last part of the url along with the parameters after `?`.

```
➜ http -v  localhost:8080/api/user/1 action==all

GET /api/user/1?action=all HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: localhost:8080
User-Agent: HTTPie/0.9.8

HTTP/1.1 200 OK
content-length: 11
content-type: application/json; charset=utf-8
date: Sun, 28 Mar 2021 09:17:26 GMT
server: Aleph.js

{
    "name": {}
}


# Server output:
DEBUG compile '/api/user/[name].ts' in 1ms
req:  Request {}
req.params:  { name: "1action=all" }
req.params.action:  undefined
```

I suppose this isn't the expected behavior. Is this a bug? Am I doing something wrong?

**Comment by ije** [comment]
this error means your api endpoint doesn't exist, i already fixed it.

**Comment by bergercookie** [comment]
But my endpoint does exist since I've put a file under `/api/user.ts` and I'm making a request like the following: `/api/user?action=all`

> i already fixed it.

Is it fixed? The error still persist after `aleph upgrade`:

```sh
14:01:20 ➜ aleph --version
aleph.js 0.3.0-alpha.20
deno 1.8.1+2f9d7c0
v8 9.0.257.3
typescript 4.2.2
```

**Comment by ije** [comment]
oh, sorry! seems the api routing is not match the search `?action=all`, i will fix it asap, thanks!

**Comment by ije** [comment]
try `/api/user/[action].ts` instead

**Comment by bergercookie** [comment]
> try /api/user/[action].ts instead

Now, having renamed my file from `user/[name].ts` to `user/[action.ts]` when I make an HTTP request (`GET /api/user/1?action=all`) it still doesn't parse the parameters correctly: 

```
INFO Server ready on http://localhost:8080/
req:  Request {}
req.params:  { action: "1action=all" }
req.params.action:  1action=all
```

Regarding the request `GET /api/user?action=all` I'm now getting an 404 instead of a 500 error like previously. But still, that's not the expected behavior. I would expect that this request would have been served by the `/api/user.ts` (or `/api/user/index.ts`) file and have the `action=all` be part of the `req.params` object.

Thanks for the quick reply and support! :)

**Comment by ije** [comment]
fixed, pls upgrade to **alpha.22**, thanks
